version: '3.8'

services:
  angular:
    image: node:20-alpine
    container_name: hasaki-angular
    working_dir: /app
    command: >
      sh -c "npm install -g @angular/cli@latest &&
             if [ ! -d "node_modules" ]; then npm install; fi &&
             ng serve --host 0.0.0.0 --disable-host-check"
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app
      - ../suitecrm:/suitecrm
    networks:
      - hasaki-network
    environment:
      - NODE_ENV=development

networks:
  hasaki-network:
    driver: bridge
