version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hasaki-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hasaki
      - MYSQL_USER=hasaki
      - MYSQL_PASSWORD=hasaki
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../suitecrm:/suitecrm
    networks:
      - hasaki-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hasaki-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../suitecrm:/suitecrm
    networks:
      - hasaki-network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  hasaki-network:
    driver: bridge
